### ISSUE TITLE
Issue with Option list without Default Select option

### ISSUE THREAD

**Issue by lhuria94** [edwardfhsiao/react-inputs-validation#10]
Hi, I am trying to use Select Component and as the document suggests it needs to have the value in the format mentioned below.

`[{id: '1', name: 'Twin Peaks'}]`

But using this format throws this error:
`Uncaught TypeError: Cannot read property 'name' of undefined in Select.js:384`

Where it works correctly when the first option is passed like:
```
[{id:"", name: "Select Country"},
{id:"United States", name: "United States"}]
```

That means the first id has to be blank. Please confirm if this is intentional.

**Comment by lhuria94** [comment]
`sss`

**Comment by lhuria94** [comment]
But using this format throws this error:
`Uncaught TypeError: Cannot read property 'name' of undefined in Select.js:384`

Where it works correctly when the first option is passed like:
```
[{id:"", name: "Select Country"},
{id:"United States", name: "United States"}]
```

That means the first id has to be blank. Please confirm if this is intentional.

**Comment by edwardfhsiao** [comment]
Hi, if you are providing [{id:"", name: "Select Country"}],  then default value for that should be ''
for example, this ```this.state.movie``` matches the first item in the optionList array
```js
this.state={
  movie: ''
}
...
<Select
  value={movie}
  optionList={[
    { id: '', name: 'Please Select a movie' },
    { id: 0, name: 'Twin Peaks' },
    { id: 1, name: 'Lion King' },
    { id: 2, name: 'American Beauty' }
  ]}
>
```

for the Select with non empty default value, you should provide non empty value.
```js
this.state={
  movie: '0'
}
...
<Select
  value={movie}
  optionList={[
    { id: 0, name: 'Twin Peaks' },
    { id: 1, name: 'Lion King' },
    { id: 2, name: 'American Beauty' }
  ]}
>
```

the key here is that the value you are providing must matches the id of the first item of the array

**Comment by lhuria94** [comment]
Got it. Thanks a lot @edwardfhsiao :)
