### ISSUE TITLE
validationOption.custom

### ISSUE THREAD

**Issue by DecentralizedIT** [edwardfhsiao/react-inputs-validation#11]
validationOption.custom | Opt | Func | Custom function that returns isValid (inputValue) => { return true|false; }

- https://github.com/edwardfhsiao/react-inputs-validation/blob/master/src/js/Inputs/Textbox.js ln: 107 - inputValue can't be set.

**Comment by edwardfhsiao** [comment]
where is ```validationOption.custom```?

Sorry I don't get what you mean

**Comment by edwardfhsiao** [comment]
thanks and check out 1.2.0
