### ISSUE TITLE
Can not search option if try to type

### ISSUE THREAD

**Issue by lhuria94** [edwardfhsiao/react-inputs-validation#14]
I am using <Select> component of this Library for display the list for Countries and as you can imagine, the list can be pretty long.

And If I try to select the option by typing as traditional select work, its not working. Is there any way to do that?

**Comment by edwardfhsiao** [comment]
I'll take it a look to see how to do

**Comment by edwardfhsiao** [comment]
Check out v1.3.1, now it is supported.

**Comment by edwardfhsiao** [comment]
update to v1.3.3 because of some bugs.

In case you are interested, if you are coding some 'area code', please check this out https://github.com/edwardfhsiao/react-custom-flag-select

**Comment by lhuria94** [comment]
Hey @edwardfhsiao 
Saved the day, Thanks a lot for this quick enhancement.

**Comment by edwardfhsiao** [comment]
i'm fixing some IE10, IE9 compatibility issue now, maybe will release a new version soon

**Comment by edwardfhsiao** [comment]
@lhuria94 just updated to v1.3.4 and v0.1.0 for react-custom-flag-select
