### ISSUE TITLE
Remove error message

### ISSUE THREAD

**Issue by ppsammartino** [edwardfhsiao/react-inputs-validation#15]
I can't seem to remove completely the error message. I only need the validation given by the callback.
So when the input is empty and onKeyUp is activated, the message 'cannot be empty' displays.
I just want to remove that message but can't with the info given in the docs.

This is a minified version of the input I'm using

<Textbox
                        type={field.type}
                        name={ name }
                        tabIndex='1'
                        classNameInput='form-control'
                        onChange={ (value, e) => {
                            this.handleChange(value, name)
                        }}
                        value={ field.value }
                        validationCallback={res => {
                            let fields = this.state.fields;
                            fields[name].isValid = !res;
                            this.setState({ fields: fields}, () => {this.validate()})}
                        }
                        onKeyUp={ e => {} }
                        validationOption={{
                            reg : reg,
                            showMsg: false,
                            regMsg: null,
                        }}
                    />

**Comment by edwardfhsiao** [comment]
Hi, I am very sorry that I have made this mistake by typing the wrong word. Thanks for your report. Please check 2.1.0, should be fixed this malfunctioning behave.
