### ISSUE TITLE
Checkbox - checked property

### ISSUE THREAD

**Issue by constantinonofrei** [edwardfhsiao/react-inputs-validation#16]
**Describe the bug**
Unable to modify the 'checked' property of the Checkbox from an outter event because the 'checked' is given by the state, and once the component is created - it can not be modified from outside.
The getDerivedStateFromProps would be the solution:

function getDerivedStateFromProps(nextProps, prevState) {
      // TODO: This was from componentWillReceiveProps()
      if ((nextProps.validate === true && prevState.validate === false) || (**nextProps.checked != prevState.checked)**){
		return {
			validate : nextProps.validate,
			**checked : nextProps.checked**
		}
	  }
	  
	  return null;

**Comment by edwardfhsiao** [comment]
This is intentional. Why do you need ```checked```? 
If you really need to know whether its checked, you can always refer to 
```js
<Checkbox
  ...
  onChange={(isAgreementChecked, e) => {
     console.log(isAgreementChecked)
     this.setState({ isAgreementChecked });
  }}

```

**Comment by constantinonofrei** [comment]
I want it to be checked/unchecked from an outter event (from a select onChange event). 
Use case:
https://www.w3schools.com/code/tryit.asp?filename=FZ8OJHGLVEZ5

**Comment by edwardfhsiao** [comment]
ok. i will take a look tomorrow

**Comment by edwardfhsiao** [comment]
@constantinonofrei Hi, please check v2.1.5. Feel free to reopen it.

**Comment by edwardfhsiao** [comment]
@constantinonofrei Hi, please check v2.1.5. Feel free to reopen it.
