### ISSUE TITLE
Regex validation & custom onChange

### ISSUE THREAD

**Issue by freddiehonohan** [edwardfhsiao/react-inputs-validation#2]
Hey Dude,

Nice simple library, however the regex test fails while checking for hexadecimal characters

`reg:/[0-9a-f]+/i, //Optional.[Bool].Default: "" Custom regex.`

I tried every combination of expression here: https://stackoverflow.com/questions/9221362/regular-expression-for-a-hexadecimal-number
It works if you type a single non hexadecimal character into the box, but if you mix them up with hex chars it doesn't work for some reason (a 64 char bitcoin key for example:  7BBC52B8945AA22779E37937D909CCA744E92310A89DD9A531D06ABD8E3A0B97).
Also, I am trying to trim the entered values of whitespace and am wondering if the Textbox's bounded onChange function could be overridden somehow?

Like the following
`onChange={this.handleChangeRecipientsPublicKey}`

Thanks,

Freddie

**Comment by edwardfhsiao** [comment]
Hi, thanks for your feedback.

1. I've tried ```reg:/[0-9a-f]+/i ``` with ```7BBC52B8945AA22779E37937D909CCA744E92310A89DD9A531D06ABD8E3A0B97```
and it works.
2.Cannot be overridden. I guess you need to manipulate the ```e.target```? I could give you that, then you can do like this ```  onChange={(res, e) => {this.handleChangeRecipientsPublicKey(res, e)}} ```

**Comment by edwardfhsiao** [comment]
as a workaround, sometimes you can do this
```js
class Index extends Component {
  constructor(props) {
    this.state = {
      address: '',
      hasAddressError: true,
      addressErrorMessage: ''
    }
    this.handleAddressChange = this.handleAddressChange.bind(this)
  }
  handleAddressChange(address) {
    let hasAddressError = true;
    let addressErrorMessage = '';
    //ETH ADDRESS VALIDATING
    if (/^0x[a-fA-F0-9]{40}$/.test(address)) {
       hasAddressError = false;
       addressErrorMessage = 'Invalid ETH Address'
    }
    this._setState({ address, hasAddressError, addressErrorMessage });
  }
  render(){
      return (
        <div>
           <Textbox
                  tabIndex="1"
                  id="address"
                  value={this.state.address}
                  type={`text`}
                  placeholder={`0x1234567890`}
                  onChange={this.handleAddressChange}
                  onBlur={() => {}}
                  validationOption={{
                    check: false
                  }}
                />
         {this.state.hasAddressError && this.state.addressErrorMessage != '' ? <div>{this.state.addressErrorMessage}</div> : ''}
        </div>
     )
  }
}
```

**Comment by edwardfhsiao** [comment]
updated to 1.0.2 now, you might get 'e' now

**Comment by freddiehonohan** [comment]
Perfect, thanks!

I'm new to react but that's exactly what I was looking for.

Cheers
