### ISSUE TITLE
Remove the default tabindex -1

### ISSUE THREAD

**Issue by Jebble** [edwardfhsiao/react-inputs-validation#20]
With accessibility in mind you should never change te natural tab order of element son the page. Especially putting items on tabindex -1 ensures that keyboard users won't be able to use these fields properly.

Since there should never be any reason to change the tabindex please remove this from the inputs.

**Comment by edwardfhsiao** [comment]
Thanks for your report, I will handle it as soon as possible.

**Comment by edwardfhsiao** [comment]
@Jebble Hi, please try v2.2.0 to see if it's fixed.

**Comment by Jebble** [comment]
I'm not actually using this in any project right now. Came across it while searching for a react validator and noticed the tabindex. Thanks for changing it and making the web a bit more accessible!
