### ISSUE TITLE
I get the error invariant violation View config not found

### ISSUE THREAD

**Issue by LeandriT** [edwardfhsiao/react-inputs-validation#22]
invariant vioation View config not found for name input make sure componenet names with capital letter

**Comment by edwardfhsiao** [comment]
Can you provide a test repo for this? Cuz I cannot reproduce it.

**Comment by edwardfhsiao** [comment]
Are u using this in a react-native project?
I don't think this works for react-native since it gots lots of html element inside.

**Comment by LeandriT** [comment]
this is not on react native project?

**Comment by edwardfhsiao** [comment]
Please provide a repo for this then, I need to test it out.

**Comment by edwardfhsiao** [comment]
> this is not on react native project?

Nope, this is for web only.
