### ISSUE TITLE
IE 11 SCRIPT1003: Expected ':' 

### ISSUE THREAD

**Issue by denisleeyt** [edwardfhsiao/react-inputs-validation#23]
I just tried to implement this library to my project, which use below dependencies, It work on Chrome and firefox, but IE console SCRIPT1003: Expected ':'  error in the Radiobox.js. 
  "devDependencies": {
    "@babel/core": "^7.4.5",
    "@babel/preset-env": "^7.4.5",
    "@babel/preset-react": "^7.0.0",
    "@babel/register": "^7.5.5",
    "autoprefixer": "^9.6.1",
    "babel-loader": "^8.0.6",
    "babel-preset-es2015-ie": "^6.7.0",
    "chai": "^4.2.0",
    "css-loader": "^3.0.0",
    "enzyme": "^3.10.0",
    "enzyme-adapter-react-16": "^1.14.0",
    "ignore-styles": "^5.0.1",
    "jquery": "^3.4.1",
    "jsdom": "^15.1.1",
    "mini-css-extract-plugin": "^0.8.0",
    "mocha": "^6.2.0",
    "postcss-loader": "^3.0.0",
    "react-hot-loader": "^4.11.1",
    "style-loader": "^0.23.1",
    "terser-webpack-plugin": "^1.3.0",
    "webpack": "^4.34.0",
    "webpack-cli": "^3.3.6",
    "webpack-dev-server": "^3.7.2"
  },
  "dependencies": {
    "@babel/polyfill": "^7.6.0",
    "bootstrap": "^4.3.1",
    "bootstrap-datetimepicker-npm": "^4.17.37-npm",
    "es6-promise": "^4.2.8",
    "isomorphic-fetch": "^2.2.1",
    "react": "^16.11.0",
    "react-dom": "^16.11.0",
    "react-inputs-validation": "^4.1.8"
  }

**Comment by edwardfhsiao** [comment]
Hi, which version are you using?
I am using "react-inputs-validation": "^4.1.8" and I did not occur error in IE.
Could you please provide a repo?

**Comment by edwardfhsiao** [comment]
and what version your IE is?

**Comment by denisleeyt** [comment]
> and what version your IE is?

IE 11, also tried 4.1.8 and 4.1.0, I tried the version 3, that's can run in my browser.
My project is webpack+babel+ReactJS

**Comment by denisleeyt** [comment]
Same error in IE 10, IE 9, I think something impact this issue.
![f1](https://user-images.githubusercontent.com/49467415/67758317-6f30cf00-fa78-11e9-98da-987a4fd739c0.PNG)
![f2](https://user-images.githubusercontent.com/49467415/67758346-7952cd80-fa78-11e9-8ecd-c9ce5829f622.PNG)

**Comment by edwardfhsiao** [comment]
please create a repo, I will look into it

**Comment by denisleeyt** [comment]
Could you run as IIS? My project is use asp.net, if you can't, I need sometime to rebuild this

**Comment by denisleeyt** [comment]
I have created a new repo, please help to text, Thanks so much for your help
https://github.com/denisleeyt/formbuilder.git

**Comment by denisleeyt** [comment]
please give me response if you have any updates, even cannot figure out solution, thanks a lot

**Comment by edwardfhsiao** [comment]
no, i can't run asp.net.

**Comment by edwardfhsiao** [comment]
is it only happened with Radiobox?

**Comment by denisleeyt** [comment]
> does it only happen with Radiobox?

I have created a repo, you can pull those code and browse in IE

**Comment by edwardfhsiao** [comment]
npm run dev and visit localhost:3000?

**Comment by denisleeyt** [comment]
Just browse the html after npm run dev, it doesn't have node server setting, let's say,
project in /a/formbuilder/index.html
url is : http://a/formbuilder/index.html

**Comment by denisleeyt** [comment]
Could you view the page? I tried to remove this library, everything is ok in IE, I have no idea why, please help to fix, many thanks.

**Comment by edwardfhsiao** [comment]
I found the problem, please wait for a sec

**Comment by edwardfhsiao** [comment]
@denisleeyt Hi, please try react-inputs-validation@4.1.9, the issue should be fixed. Thank you for your report!

**Comment by denisleeyt** [comment]
Thanks so much, it's work!! very helpful
