### ISSUE TITLE
Improve TypeScript support

### ISSUE THREAD

**Issue by rxkevin** [edwardfhsiao/react-inputs-validation#25]
![Screenshot 2020-12-01 at 18 04 46](https://user-images.githubusercontent.com/72786689/100765311-0ac10b80-3400-11eb-8353-bc916a67c7e1.png)

Currently, no TS declarations are exported with the package, which does not make it developer-friendly. Even though, I see typescript is being used in the development of this package. Please, just add `"declaration": true,` to your tsconfig, and modify your build scripts accordingly if needed.

**Comment by edwardfhsiao** [comment]
Hi @rxkevin, I have updated the version to 4.6.0, not sure if it works, can you check it out?

**Comment by rxkevin** [comment]
First of all, forgot to mention, good work on this package!

One step closer, types are now included in the package, however, `index.d.ts` must be in the root of your package, where now it is in the `root/lib` directory. As mentioned, you will probably need to modify your build script, or set ` "declarationDir": "./"` in tsconfig.

![Screenshot 2020-12-02 at 09 17 41](https://user-images.githubusercontent.com/72786689/100841019-5c5cab00-347f-11eb-8fda-96f328a0e3d3.png)

**Comment by rxkevin** [comment]
Also, type definitions could also be improved for each component. A lot of parameters use abstract types, which is not that helpful either.

![Screenshot 2020-12-02 at 09 22 32](https://user-images.githubusercontent.com/72786689/100841572-22d86f80-3480-11eb-9909-3d46fee66c9d.png)

**Comment by edwardfhsiao** [comment]
Is it possible that you can create a PR for this?

**Comment by rxkevin** [comment]
I'm short on time but will I try to make it this week hopefully.

**Comment by edwardfhsiao** [comment]
Is v4.6.2 meeting the expectation?

**Comment by edwardfhsiao** [comment]
Does v4.6.2 meet the expectation?

**Comment by RokasAniss** [comment]
It does! We can close this issue now.

**Comment by edwardfhsiao** [comment]
@all-contributors please add @RokasAniss  for code
