### ISSUE TITLE
Can you have maxLength also as an option?

### ISSUE THREAD

**Issue by popeyedvl** [edwardfhsiao/react-inputs-validation#4]
It is a great component, but it would be better if you can find a way to propagate maxlength also for TextBox .
Is that possible?
Thank you!

**Comment by edwardfhsiao** [comment]
sure, in addition, you can do like this
```js
  componentDidMount() {
    const { verifyCode } = this.state;
    Object.keys(verifyCode).filter(k => {
      document.getElementById(`verifyCode${k}`).setAttribute('maxlength', '1');
    });
  }
```

**Comment by edwardfhsiao** [comment]
Checkout 1.0.4, now you can provide ```maxLength``` to both Textbox and Textarea.

Please note: since ```maxLength``` does not work very well with the type of ```number``` in react, I manually returned when the value length greater than ```maxLengh``` in onChange function.

```js
  onChange(e) {
    if (this.props.maxLength != '') {
      if (this.input.value.length > Number(this.props.maxLength)) {
        return;
      }
    }
    ...
  }
```

**Comment by popeyedvl** [comment]
Great thank you!
